import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The legal terms governing use of the Inzterior website — separate from the project payment, contract, and warranty terms described on our Terms page.",
};

const SECTIONS = [
  {
    title: "1. Who these terms apply to",
    body: (
      <>
        <p>
          These Terms of Service govern your use of the website located at{" "}
          <strong className="text-[var(--ink)]">inzterior.com</strong> (the &ldquo;Site&rdquo;),
          operated by Istory Design Studio, trading as Inzterior (SSM Reg. No. SA0647003-M),
          based in Horizon Hills, Iskandar Puteri, Johor, Malaysia (&ldquo;Inzterior&rdquo;,
          &ldquo;we&rdquo;, &ldquo;us&rdquo;).
        </p>
        <p className="mt-4">
          By browsing or using this Site, you agree to these terms. If you don&apos;t agree,
          please don&apos;t use the Site.
        </p>
        <p className="mt-4">
          These terms cover use of the <em>website only</em>. They do not cover the scope,
          pricing, payment structure, or warranty of any interior design or renovation project
          — that&apos;s governed by a separate written contract signed before project work
          begins. See our{" "}
          <a href="/terms" className="border-b border-[var(--ink)] hover:border-[var(--accent)] hover:text-[var(--accent)]">
            Our Terms
          </a>{" "}
          page for how project payments, contracts, and warranty work.
        </p>
      </>
    ),
  },
  {
    title: "2. Content and intellectual property",
    body: (
      <>
        <p>
          All text, images, logos, layouts, and design elements on this Site are owned by
          Inzterior or used with permission, unless stated otherwise. You may view and share
          pages of this Site for personal, non-commercial purposes, but you may not reproduce,
          copy, or redistribute Site content — including portfolio photography — for
          commercial use without our written consent.
        </p>
        <p className="mt-4">
          Reference imagery used to illustrate design direction (where noted) is not
          Inzterior&apos;s own work and remains the property of its respective owners.
        </p>
      </>
    ),
  },
  {
    title: "3. The estimate calculator and quote tools",
    body: (
      <p>
        Any pricing figures generated by tools on this Site (such as the estimate calculator)
        are indicative only, based on the inputs you provide. They are not a formal quote or
        offer and do not form part of any contract. A binding, itemised quote is only issued
        after a proper site visit or floor plan review, as described on our{" "}
        <a href="/estimate" className="border-b border-[var(--ink)] hover:border-[var(--accent)] hover:text-[var(--accent)]">
          Estimate
        </a>{" "}
        page.
      </p>
    ),
  },
  {
    title: "4. No warranty on Site availability",
    body: (
      <p>
        We try to keep this Site accurate and available, but we make no guarantee that it will
        be error-free, uninterrupted, or free of viruses or other harmful components. We may
        update, suspend, or remove parts of the Site at any time without notice.
      </p>
    ),
  },
  {
    title: "5. Limitation of liability",
    body: (
      <p>
        To the fullest extent permitted by Malaysian law, Inzterior is not liable for any
        indirect, incidental, or consequential loss arising from your use of this Site,
        including reliance on indicative pricing or portfolio content. Nothing in this section
        limits liability that cannot lawfully be excluded.
      </p>
    ),
  },
  {
    title: "6. Links to other sites",
    body: (
      <p>
        This Site may link to third-party sites (such as the SSM company search portal) for
        your reference. We don&apos;t control and aren&apos;t responsible for the content of
        external sites.
      </p>
    ),
  },
  {
    title: "7. Changes to these terms",
    body: (
      <p>
        We may update these Terms of Service from time to time. Changes take effect once
        posted on this page. Continued use of the Site after a change means you accept the
        updated terms.
      </p>
    ),
  },
  {
    title: "8. Governing law",
    body: (
      <p>
        These terms are governed by the laws of Malaysia. Any dispute arising from use of this
        Site is subject to the exclusive jurisdiction of the Malaysian courts.
      </p>
    ),
  },
  {
    title: "9. Contact",
    body: (
      <p>
        Questions about these terms can be sent to{" "}
        <a href="mailto:inquiry@inzterior.com" className="border-b border-[var(--ink)] hover:border-[var(--accent)] hover:text-[var(--accent)]">
          inquiry@inzterior.com
        </a>
        .
      </p>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <>
      <section className="border-b border-[var(--line)] py-20">
        <div className="mx-auto max-w-3xl px-6">
          <span className="mb-4 block text-sm font-semibold text-[var(--accent)]">
            Legal
          </span>
          <h1 className="text-3xl font-semibold sm:text-4xl">Terms of Service</h1>
          <p className="mt-4 text-sm text-[var(--ink-soft)]">Last updated: 30 July 2026</p>
          <p className="mt-6 max-w-2xl text-[var(--ink-soft)]">
            This page covers the legal terms for using this website. It&apos;s a general
            template and hasn&apos;t yet been reviewed by a Malaysian lawyer — treat it as a
            placeholder pending that review, not final legal advice. If you&apos;re looking
            for how project payments, contracts, and warranty work, see{" "}
            <a href="/terms" className="border-b border-[var(--ink)] hover:border-[var(--accent)] hover:text-[var(--accent)]">
              Our Terms
            </a>{" "}
            instead.
          </p>
        </div>
      </section>

      <section className="py-16">
        <div className="mx-auto max-w-3xl px-6">
          <div className="flex flex-col gap-10">
            {SECTIONS.map((section) => (
              <div key={section.title}>
                <h2 className="mb-3 text-lg font-semibold">{section.title}</h2>
                <div className="max-w-2xl text-sm leading-relaxed text-[var(--ink-soft)]">
                  {section.body}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
